# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Paths' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Paths
  pod 'Socket.IO-Client-Swift', '~> 11.1.3'
  pod 'LFLiveKit'
end
